  language: python
  python:
    - "3.6"

  install:
  - pip install -r requirements.txt
  
  script:
    - pytest --cov app

  branches:
    only:
  - ch-configure-procfile-161858951
  - develop

  after_success:
  - "codecov"
  - coveralls