  language: python
  python:
    - "3.6"

  install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  
  script:
    - pytest --with-coverage

  after_success:
  - "codecov"
  - coveralls