  language: 
    - python
  python:
    - "2.7"
    - "3.6"

  install:
    - pip install -r requirements.txt
    - pip install nose
    - pip install coverage
    - pip install coveralls
    
  ignore:
    - tests/
 
  script:
    - nosetests --with-coverage --cover-package=app

  after_success:
    - coveralls
